### ISSUE TITLE
Apparently I've been removed as maintainer

### ISSUE THREAD

**Issue by rpanai** [conda-forge/bar_chart_race-feedstock#5]
@conda-forge-admin I received a mail informing me _You’ve been removed from the bar_chart_race team on the conda-forge organization._ I wrote the first recipe and I added @tdpetrou as maintainer as he is the author of the code. I'd like to know why I've been removed and if it's possible to revert.

**Comment by tdpetrou** [comment]
Hey Roberto,

I have no idea why that would be the case. You'll have to contact the
conda-forge maintainers for an answer.

Hope all is well,
Ted

**Comment by rpanai** [comment]
@tdpetrou it looks like in [this](https://github.com/conda-forge/bar_chart_race-feedstock/pull/4/commits/f76185806d4b75d3394f96cf9b65dedef9c0bd46) commit I was removed as maintainer. Funnily enough it was me that then merged to master that commit. @conda-forge-coordinator how can we revert this?

**Comment by beckermr** [comment]
So the admin and coordinator users are bots. To get added back, any of the current maintainers can add your GitHub username to the recipe in a pr. Once that pr is merged, our bots will add you back.

**Comment by rpanai** [comment]
@tdpetrou do you mind to accept this [PR](https://github.com/conda-forge/bar_chart_race-feedstock/pull/6)
